model Aboutme {
    public_name string? 
    title string?
    intro string?
    bio   string? 
    summary string?
    lincenseID string?
} 
model SocialLinks {
    linkedin string?
    facebook string?
    instantgram string?
    twitter string?
    globeforum string?
    github     string?
    lander string?

}
model Finance {
    namespace string?
    
}